import './globals.css';
import BodyContainer from './_components/BodyContainer';


export const metadata = {
  title: 'First Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <BodyContainer>
        { children }
      </BodyContainer>
    </html>
  )
}
