import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import Footer from './Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'First Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className='dark bg-gray-100 text-gray-950 dark:bg-gray-950 dark:text-white'>
          <NavBar />
          <div className='' style={{minHeight:'calc(100vh - 4rem'}}>
            {children}
          </div>
          <Footer />
      </body>
    </html>
  )
}
